version: '2'

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: digitaleq
      POSTGRES_USER: digitaleq
      POSTGRES_DB: runner
    ports:
      - "5433:5432"
    networks:
      - eq-env

  secure-messaging-api:
    build: .
    restart: always
    networks:
      - eq-env
    ports:
      - "5000:5000"

networks:
  eq-env:
    driver: bridge
